manifest:
  remotes:
    - name: keychron
      url-base: https://github.com/Keychron

  projects:
    - name: zmk
      remote: keychron
      revision: keychron_bpro
      import: app/west.yml

  self:
    path: config
